### ISSUE TITLE
Missing interface for order replacement

### ISSUE THREAD

**Issue by codedot** [ripple/ripple-lib#722] opened 2016-07-08 11:23 UTC
[`OfferCreate`](https://ripple.com/build/transactions/#offercreate) has an optional parameter `OfferSequence` to specify an order to delete before creating a new one. However, in the latest `ripple-lib` version the `prepareOrder()` routine does not support that option. This option needs to be implemented to save fees and time for market makers.

**Comment by mDuo13** [comment] 2016-07-14 19:42
this is a dupe of #700

**Comment by clark800** [comment] 2016-07-19 20:55
Closing as duplicate

**Closed by clark800** 2016-07-19 20:55 UTC
