### ISSUE TITLE
Relations between transactions and balances

### ISSUE THREAD

**Issue by florentweiler** [ripple/ripple-lib#1501] opened 2021-08-03 13:17 UTC
Hello, 

I have a question concerning some behaviors in the API that I find it hard to explain, 
more precisely between the relationship that the transactions and the balances of an account share over time.

From my point of view, I would always expect some transaction to alter the balances of an account depending on what is actually happening in the transaction, however this does not seem to be the logic taken by the API. Let's have a concrete (quite simple) example to explain what I mean.

Let's say we take this random account: rGBP6jP1a7pJF7AtnEUa5Q4T2dwZxcQaWG which contains a few transactions.

- First of all the first transaction involving this account is this one : 

AEFD4306CA9F3CBEB991D4898C94DEFB2EA88C348BE1311E5C6758E214E28FE7

we can see in this transaction that the given account receives 20 XRP from this address: raMNd49mErtMaJMA7QUXWE8eL6Ftt7LWQY and it is the only transaction that perform a balance change for our initial account within ledger 62965182 meaning that at this ledger only this transaction could have an effect on the balances of this account

Now if I am performing a getBalances for this this address at this ledger I get : 
```json
[
    { "currency": "XRP", "value": "20" },
    {
      "currency": "EUR",
      "counterparty": "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq",
      "value": "0.468895474611"
    }
  ]
```

here we can see that the account owns some EUR that were never shown in the transaction that created it, how am I supposed to retrieve this information ? 

- Second, let's get a big further in time and jump to this transaction that the account made: 5FF49424A4314292DC534C3E5BDA15912B0542D8B7E492C15B40237A8E34D3CE

here we can see that the account ordered some BTC and the order has been partially-filled, however the getBalances for this account at ledger 62965412 does not show any BTC : 

```json
[
    { "currency": "XRP", "value": "919.999746" },
    {
      "currency": "EUR",
      "counterparty": "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq",
      "value": "0.468895474611"
    }
  ]
```

Can you explain me what I am doing wrong with my analysis ?

**Comment by natenichols** [comment] 2021-08-03 20:27
Hi @florentweiler, can you provide a code snippet and/or information about what server you're connecting to?

**Comment by natenichols** [comment] 2021-08-03 20:59
I'm beginning to think this might be a bug:

When I run
```js
const balances = await API.getBalances(`rGBP6jP1a7pJF7AtnEUa5Q4T2dwZxcQaWG`, {ledgerVersion: 62965182 })
```

I get:

```js
[
  { currency: 'XRP', value: '20' },
  {
    currency: 'EUR',
    counterparty: 'rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq',
    value: '0.468895474611'
  }
]
```

Which is weird, because that's not the balance at that `ledgerVersion`, which I can confirm w/ some [Websocket Requests](https://xrpl.org/websocket-api-tool.html#account_lines)

```js
{
  "command": "account_lines",
  "account": "rGBP6jP1a7pJF7AtnEUa5Q4T2dwZxcQaWG",
  "ledger_index": 62965182
}
```
W/ the websocket API, I get

```js
"result": {
    "lines": []
}
```
And when I leave off the `ledger_index: 62965182` , which causes it to default to `ledger_index: "validated"` I get

```js
result: {
    "lines": [
      {
        "account": "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq",
        "balance": "0.468895474611",
        "currency": "EUR",
        "limit": "0",
        "limit_peer": "0",
        "no_ripple": true,
        "no_ripple_peer": false,
        "quality_in": 0,
        "quality_out": 0
      }
    ],
}
```

Which exactly matches the response from `getBalances`.

What I'm thinking is that `LedgerVersion` is not getting propagated to the `account_lines` request. This is just what I'm seeing from playing w/ this request for `rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq`, and I haven't tested elsewhere and/or repro'd this for other situations.

**Comment by florentweiler** [comment] 2021-08-04 08:00
Thanks for your reply, here is the code snippet (quite simple) : 

```js
const RippleAPI = require('ripple-lib').RippleAPI;
const api = new RippleAPI({
    server: 'wss://s2.ripple.com' // Public rippled server
    // server: 'wss://xrplcluster.com',
});


async function fetchBalancesOverTime() {
    await api.connect();
    let transactions = await api.getTransactions('rGBP6jP1a7pJF7AtnEUa5Q4T2dwZxcQaWG', {earliestFirst: true});
    for (let tx of transactions) {
        if(tx.outcome.balanceChanges['rGBP6jP1a7pJF7AtnEUa5Q4T2dwZxcQaWG'])
        {
            console.log({id: tx.id, ledgerVersion: tx.outcome.ledgerVersion})
            console.log({balanceChanges: tx.outcome.balanceChanges['rGBP6jP1a7pJF7AtnEUa5Q4T2dwZxcQaWG']})
            let balances = await api.getBalances('rGBP6jP1a7pJF7AtnEUa5Q4T2dwZxcQaWG', {ledgerVersion: tx.outcome.ledgerVersion});
            console.log({balances})
        }
    }
     await api.disconnect();
}

fetchBalancesOverTime();
```

As you can see I am using public rippled servers, (also tried with my private node but it was the same)

I actually added all EUR amount the address received / sent which correspond to any result of the getBalance : 0.468895474611
that would mean thatas you said there is a problem with ledgerVersion, from what I understand it works for XRP balances but not for any IOU.

**Comment by natenichols** [comment] 2021-08-04 22:41
@florentweiler, thanks so much for opening this issue. 

@mvadari just put up a fix, and this issue will be auto-closed when that PR is merged.

**Closed** 2021-08-06 17:18 UTC
