### ISSUE TITLE
Tests are network-dependent

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1108] opened 2019-12-12 05:29 UTC
With my home internet connection (Cox cable) the connection tests fail:

```
  Connection
    ✓ default options
    ✓ trace
    ✓ with proxy
    ✓ Multiply disconnect calls
    ✓ reconnect
    ✓ NotConnectedError
(node:56246) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_plus__WEBPACK_IMPORTED_MODULE_0__.ok.apply(assert_plus__WEBPACK_IMPORTED_MODULE_0__.ok, arguments)

    at Object.AssertDiff [as default] (/Users/user/github/ripple/ripple-lib/node_modules/assert-diff/lib/webpack:/lib/index.mjs:5:1)
    at /Users/user/github/ripple/ripple-lib/test/connection-test.ts:122:13
(node:56246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:56246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Instead of getting `NotConnectedError`, I get the `ConnectionError` from here: https://github.com/ripple/ripple-lib/blob/develop/src/common/connection.ts#L300 (the connection times out after 2 seconds).

However, using a different internet connection (in my case, a VPN) resolves the issue; the test passes.

**Comment by FKSRipple** [comment] 2019-12-13 07:16
fwiw I can't reproduce what you're seeing on my local machine (all tests pass on my macbook when disconnected from the wifi). Make sure that you're on latest `develop` branch with a fresh `yarn install`?

**Comment by intelliot** [comment] 2019-12-13 07:28
Yes, the only difference is my internet connection. I think this may be related to the “different failing tests” mentioned in another issue. Ideally our tests wouldn’t rely on network behavior; there should be some way to ‘mock’ or fake a connection for testing purposes.

**Comment by FKSRipple** [comment] 2019-12-13 11:44
Oh, interesting. I can't tell from the OP, but which test is failing? (all posted tests appear to have ✓ marks)

**Comment by intelliot** [comment] 2019-12-15 06:42
These two fail:
```
  2 failing

  1) Connection
       should throw NotConnectedError if server not responding :
     Error: Timeout of 200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/elliotlee/ripple/ripple-lib/test/connection-test.ts)
  

  2) Connection
       reconnection test
         reconnect on several unexpected close:
     Error: Timeout of 70001ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/elliotlee/ripple/ripple-lib/test/connection-test.ts)
```

**Comment by mvadari** [comment] 2021-09-14 21:33
I don't have any tests failing even when I turn my internet off, so I'm going to close this issue now.

**Closed by mvadari** 2021-09-14 21:33 UTC
Labels: good first issue, ripple-lib 2.0 (xrpl.js)
