### ISSUE TITLE
GlobalBigNumber error

### ISSUE THREAD

**Issue by hoangphuongcs** [ripple/ripple-lib#925] opened 2018-08-07 10:15 UTC
I got an error, can you help me? thanks! 
orderbookchanges.js:5 Uncaught TypeError: GlobalBigNumber.another is not a function
    at Object../node_modules/ripple-lib-transactionparser/src/orderbookchanges.js (orderbookchanges.js:5)
    at __webpack_require__ (bootstrap:767)
    at fn (bootstrap:130)
    at Object../node_modules/ripple-lib-transactionparser/src/index.js (index.js:8)
    at __webpack_require__ (bootstrap:767)
    at fn (bootstrap:130)
    at Object.<anonymous> (utils.js:4)
    at Object../node_modules/ripple-lib/dist/npm/ledger/parse/utils.js (main.js?v=fbdbadbd5b240b86842a:244748)
    at __webpack_require__ (bootstrap:767)
    at fn (bootstrap:130)

**Comment by 0xngoubou** [comment] 2018-08-08 03:32
Yes, i have really install bignumber.js verion 7.2.1 in my project **"my-project/node_modules/bignumber.js"**
And there is bignumber.js lib in "**my-project/node_modules/ripple-lib-transactionparser/node_modules/bignumber.js**", but "version": "4.1.0"
Please help me, thank you so much.

**Comment by intelliot** [comment] 2018-08-08 06:08
When building ripple-lib for use in a browser, you should use `yarn build` (or `npm build`) and use the file in the `./build/` directory.

The error looks related to a problem with importing bignumber.js. Can you upload or link to an example project which shows this problem?

**Comment by intelliot** [comment] 2018-08-08 06:10
It looks like you may be using webpack. If possible, please post your webpack config as well.

**Comment by intelliot** [comment] 2018-08-10 22:06
@0xngoubou I wasn't able to reproduce this error. I'll wait up to 1 week to hear from you before closing this issue. After that, you can re-open it if needed.

**Comment by szymonlesisz** [comment] 2019-04-25 14:19
any update on this? i've got the same issue

**Comment by okipol88** [comment] 2019-06-13 20:34
I have a reproducable example:
This works fine on its own
[https://github.com/okipol88/airgap-coin-lib/tree/feature/add-coin-xrp](url)
When it is linked to be used here - iit fails with the aforementioned error
[https://github.com/okipol88/airgap-vault/tree/feature/add-coin-xrp](url)

I've seen a similar issue here (I guess):
hildjj/node-cbor#88

**Comment by okipol88** [comment] 2019-06-13 21:25
Ok so the reason for this is that there is a dependecy to 

> ripple-lib-transactionparser
Which has a dependency on 

`"bignumber.js": "~2.0.3"`

When webpack packs thing up ... it packs the latest BigNumber and because this is referenced not by packages.json which references v8.0.0+ => then it cannot find the the `another` method which was renamed in v.4.x.x to `clone`. So I guess it is time for an update 😄 .

**Comment by intelliot** [comment] 2019-06-13 21:44
Good catch. Could you open a PR?

**Comment by okipol88** [comment] 2019-06-14 05:16
@intelliot ![Yes can doo!](https://media3.giphy.com/media/DgLsbUL7SG3kI/giphy.gif)

Just have to find some time today 😃

**Comment by okipol88** [comment] 2019-06-14 08:08
Ok so its harder to go down the "good path". I am getting some errors ... well I changed the bignumber.js references + calls. Then I get some weird errors when I wanted to test it so I  can pull local transactionparser to ripple-lib then ripple-lib to airgap-coin-lib. So then maybe someone more familiar with the transactionparser (or not an npm/javascript newbie like me) could update it for ripple-lib to also get it? Will try later on if no one attempts.

**Comment by okipol88** [comment] 2019-06-15 09:58
Ok - we will see how this goes guys ;). I've run some unit tests on debian also. For unrelated packages I had some fails but it does not seem to be related to bignumber upgrade.
ripple/ripple-lib-extensions#40

**Comment by okipol88** [comment] 2019-07-06 06:59
@intelliot The topic is stagnant for some time... Who can merge my pull request so that a newer version of ripple-lib-extensions can be refferenced?

**Comment by intelliot** [comment] 2019-07-08 16:43
@okipol88 I can. What do you mean by: "For unrelated packages I had some fails"?

**Comment by okipol88** [comment] 2019-07-08 18:18
@intelliot I mean npm packages from ripple lib extensions which I did not change had some failures. You can check on your own. I tested it in Debian environment from within windows Store "Debian App".

**Comment by okipol88** [comment] 2019-07-27 09:54
@intelliot Can you publish the ripple lib transaction parser?

**Comment by szymonlesisz** [comment] 2019-08-01 07:31
Since it wasn't released yet i want to share my solution for that issue.
The real problem here was not a dependency itself but invalid webpack configuration where top-level and nested dependencies was not resolved correctly.
I had it set like:
```
resolve: {
        modules: [SRC, NODE_MODULES],
 },
```
where `NODE_MODULES` was a variable with absolute path to the project node_modules
When i changed it to:
```
resolve: {
        modules: [ SRC, 'node_modules' ],
},
```
webpack starts to resolve nested deps correctly. Parent project uses `bignumber.js@9.0.0` while ripple-lib uses own, nested `@2.0.3`

**Comment by intelliot** [comment] 2019-08-01 21:57
@okipol88 ripple-lib-transactionparser v0.8.0 https://github.com/ripple/ripple-lib-extensions/releases/tag/0.8.0

**Comment by r0bertz** [comment] 2019-11-11 08:52
Hi, Elliot, can you publish a new version of https://www.npmjs.com/package/ripple-lib-value too? Thanks!

**Comment by mvadari** [comment] 2021-09-14 21:42
Assuming this has been resolved, given that there's a PR, `bignumber.js`'s version in this repo is greater than `8.0.0` (it's `9.0.0`) and also `BigNumber.another` isn't used in the repo, and no one has commented on this PR in almost 2 years. If someone still has this bug, please reopen this issue.

**Closed by mvadari** 2021-09-14 21:42 UTC
