### ISSUE TITLE
memory build up when doing repeated calls to getTransactions

### ISSUE THREAD

**Issue by southbite** [ripple/ripple-lib#1301] opened 2020-06-26 06:55 UTC
Hi there! 

We are doing repeated calls to getTransactions - with a from and to ledger version range, as we are watching the ledger for incoming transactions on a specific account. This is on a long-lived connection (days).

When using the old ripple-lib - v1.3.4 - our memory usage on the server remains stable.
When using v1.7.1 - we get a linear increase in memory consumption until node runs out of heap and our service restarts. A linear increase is in keeping with the service we have that repeatedly gets the transactions, as it runs every few seconds.

We wrap ripple-lib in a utility library, so I created a test in the library that performs getTransactions then does a GC and heapdump (rinse-repeat 9 times). With the old version of ripple-lib - our heapdumps stay the same size. WIth v1.7.1 they grow linearly - in the same fashion they do on our server.

I then compared the heap dumps - and found large amounts of transaction hashes in the deltas between the oldest and newest heapdumps of the test set, I then looked at what was retaining them, and it looks like the RequestManager is holding on to them, on further investigation I realized that better men or women than me (that would be the engineers who I am speaking to now :) ) would be able to work out how the request manager works in v1.7.1

Sorry - I am rambling a bit, my parting questions are:

- would you like the heap dumps? They are about 24MB compressed.
- could this be a usage thing on our part, and this is expected behaviour - are we doing something silly by having long-lived connections - should we destroy connections with every request or N requests?

**Comment by intelliot** [comment] 2020-06-26 07:14
Hi, thanks for opening this issue!

This does sound like a memory leak in the RequestManager. (Pinging @FredKSchott - who knows more about this than me - to see if he could help look into this.)

Sure, I'd like the heap dumps. Given the size, I imagine it may make sense to upload them to a sharing service e.g. Google Drive. You can use the email address in my GitHub profile.

No, this is not expected behavior. I think long-lived connections are a good thing.

**Comment by southbite** [comment] 2020-06-26 10:13
You should receive an email in your github.public@intelliot.com mailbox - I also added the example test code (for reference purposes)

**Comment by southbite** [comment] 2020-06-26 11:16
NB: We may have detected a more gradual increase in memory - since we deployed the old version of ripple-lib, so I dont want you guys going down a rabbit hole yet - as it may be something in the way we are consuming ripple-lib - that is just more apparent because the newer version caches data. If possible lets put this on hold until we are doubly absolutely sure. SO sorry - we don't want to waste anyone's time.

**Comment by southbite** [comment] 2020-06-26 11:35
Ok - nailed it. I think... If you look here at the RequestManager: https://github.com/ripple/ripple-lib/blob/develop/src/common/connection.ts#L233

```
  resolve(id: number, data: any) {
    const {timer, resolve} = this.promisesAwaitingResponse[id]
    clearTimeout(timer)
    resolve(data) 
    // delete this.promisesAwaitingResponse[id] - this is not here, or anywhere ese we could discern
  }
```

You will see that the promisesAwaitingResponse Key/Value store is not being cleared of the awaiting promise - even when it has been resolved, or rejected etc. This causes a buildup of promises in memory. I inserted the code that deletes the resolved promise from the promisesAwaitingResponse - and bingo - our heap dumps are not growing anymore.

**Comment by intelliot** [comment] 2020-06-26 17:03
That makes sense to me! Would you like to open a PR? (Very appreciated)

(I wasn't able to run your test code since it relies on some other files that were not included.)

**Comment by southbite** [comment] 2020-06-26 21:34
sure - I'll look at it over the weekend.

**Comment by southbite** [comment] 2020-06-27 14:33
https://github.com/ripple/ripple-lib/pull/1302 
but... I found some things I couldn't understand in the tests - I was getting failures at connection-test: propagates RippledError data 

This is because I was getting multiple resolve events for the same request (and because we are now clearing the waiting array a "response handler not found" error is raised) - perhaps a streaming mechanism or something, I then [removed the throw if no matching available promise if found](https://github.com/ripple/ripple-lib/pull/1302/files#diff-0a9280b79cd764365023957c8532526cR284) - and all tests pass.

Am I understanding things correctly that every request should only have one waiting response, and that we don't expect to hit the same response handler over and over again - which would make this a valid fix - or are we also using this mechanism for things like streams - in which case the solution will become more complex, as we would need to handle the response handler lifecycle differently, depending on whether we are streaming or doing straight-up request response? I think Mr Schott may be the right person to weigh in on this.

**Comment by christsim** [comment] 2020-09-27 18:34
I'm using v1.8 and am experiencing the same issue.  

The heapdump has many of object related to `promisesAwaitingResponse in RequestManager@4023431`

I also have the heap dumps if that will help.

**Comment by intelliot** [comment] 2020-09-28 16:27
@christsim Are you able to try the fix in PR https://github.com/ripple/ripple-lib/pull/1302 ? (I could include it in a beta release if that would make things easier)

**Comment by christsim** [comment] 2020-09-28 19:46
> @christsim Are you able to try the fix in PR #1302 ? (I could include it in a beta release if that would make things easier)

I'm happy to try test the PR, but could you please put it in a beta release for me?

**Comment by intelliot** [comment] 2020-09-28 20:57
@christsim please try `ripple-lib@beta` (or 1.8.2-beta.0)

**Comment by christsim** [comment] 2020-09-28 22:02
> @christsim please try `ripple-lib@beta` (or 1.8.2-beta.0)

I can confirm that this build solves the memory leak and the memory has been stable.   I also don't see any of the `promisesAwaitingResponse` objects building up in the heapdump.  I have done a quick test and everything else so far seems fine too.

**Comment by intelliot** [comment] 2020-12-22 19:20
This is now fixed

**Closed by intelliot** 2020-12-22 19:20 UTC
