### ISSUE TITLE
timeout option is not working

### ISSUE THREAD

**Issue by koresar** [ripple/ripple-lib#1196] opened 2020-01-30 08:21 UTC
```js
const api = new RippleAPI({ server: "wss://s1.ripple.com", timeout: 60000 });
api.connect(); // <-- rejects in 2000 ms
```

The `api.connect()` does not respect the `timeout` option and rejects after 2000 ms. Here is the error message:
```
"Error: connect() timed out after 2000 ms. If your internet connection is working, the rippled server may be blocked or inaccessible."
```

Help!

**Comment by intelliot** [comment] 2020-01-30 09:22
This is a bug (the timeout option isn't working) and we should fix it. But why is it taking more than 2 seconds to connect to rippled -- is that what you expect? (Is your internet connection really that slow?)

**Comment by koresar** [comment] 2020-01-30 11:16
The machine which is connecting to the rippled is very weak. It takes about
2.1 seconds to connect to r1 over the pacific ocean using websockets. 😅

**Comment by intelliot** [comment] 2020-01-31 08:41
Thanks. I think we should make the timeout option work, and we should also increase the default timeout to 5 seconds (5000 ms).

**Comment by nickewansmith** [comment] 2020-02-04 15:48
Would it make sense to add a `requestTimeout` and `connectionTimeout` to ripple api options?, with the default for `connectionTimeout` set to 5000ms.

**Comment by intelliot** [comment] 2020-02-04 17:02
I’m happy either way — I’ve not needed to adjust the timeouts personally but I can see that being useful for some slower machines/networks.

**Comment by kincaidoneil** [comment] 2020-02-06 23:12
I'm also experiencing this error, `NotConnectedError: Error: connect() timed out after 2000 ms. If your internet connection is working, the rippled server may be blocked or inaccessible.` when running a test using S1 from DigitalOcean East.

It looks like the `connectionTimeout` property adjusts this (and is included in the TypeScript types), but doesn't work because it's not included in the [schema here](https://github.com/ripple/ripple-lib/tree/c17827e030fec150bff22035cfccf8b38315c820/src/common/schemas/input).

In the meantime, this works for me:
```
// @ts-ignore
rippleClient.connection._config.connectionTimeout = 10000
```

**Comment by southbite** [comment] 2020-04-06 19:26
Is this not a duplicate of issue #1174 ?

**Comment by koresar** [comment] 2020-04-06 21:25
I wouldn't call these duplicates. But you one can be causing another.

**Closed** 2021-02-12 07:55 UTC
